name: GDLauncher Next CI

on:
  push:
    branches:
      - master
      - releases
      - native-refactor
  pull_request:
    branches:
      - master
      - releases
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Use Node.js 14.16.0
        uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'

      - name: npm run install
        run: |
          npm i
      # - name: npm run lint
      #   run: |
      #     npm run lint
      - name: npm run release for windows
        if: matrix.os == 'windows-latest' && github.event_name == 'push'
        env:
          CI: ''
          TRAVIS_TAG: ''
          APPVEYOR_REPO_TAG_NAME: ''
          CIRCLE_TAG: ''
          BITRISE_GIT_TAG: ''
          GITHUB_ACTIONS: ''
          CI_BUILD_TAG: ''
          CSC_KEY_PASSWORD: ''
          CSC_LINK: ''
          SENTRY_DSN: ''
          SOURCE_MAPS_UPLOAD: ''
          SENTRY_AUTH: ''
        run: |
          npm run release
      - name: npm run release for mac and linux
        if: matrix.os != 'windows-latest' || github.event_name != 'push'
        env:
          CI: ''
          TRAVIS_TAG: ''
          APPVEYOR_REPO_TAG_NAME: ''
          CIRCLE_TAG: ''
          GITHUB_ACTIONS: ''
          BITRISE_GIT_TAG: ''
          CI_BUILD_TAG: ''
          SENTRY_DSN: ''
          SOURCE_MAPS_UPLOAD: ''
          SENTRY_AUTH: ''
        run: |
          npm run release

      - uses: actions/upload-artifact@v1
        if: matrix.os == 'macos-latest'
        with:
          name: MacOs Release
          path: deploy

      - uses: actions/upload-artifact@v1
        if: matrix.os == 'windows-latest'
        with:
          name: Windows Release
          path: deploy

      - uses: actions/upload-artifact@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          name: Linux Release
          path: deploy